import type { HypnosisFeature } from '../../types';

export const FEATURES: HypnosisFeature[] = [
  // TRIAL
  {
    id: 'trial_basic',
    title: '初级一般催眠',
    description: '被催眠者无意识遵循简单指示, 不能指令被催眠对象非常不愿意的行为, 强行指令会退出催眠.',
    tier: 'TRIAL',
    costType: 'PER_MINUTE',
    costValue: 5,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入简单动作指示...',
  },

  // VIP 1
  {
    id: 'vip1_stats',
    title: '角色状态可视化',
    description: '解锁身体属性查看APP.',
    tier: 'VIP1',
    costType: 'ONE_TIME',
    costValue: 0,
    isEnabled: false,
  },
  {
    id: 'vip1_senses',
    title: '味嗅觉修改',
    description: '将一种味道修改成另一种味道.',
    tier: 'VIP1',
    costType: 'PER_MINUTE',
    costValue: 4,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '目标味道 -> 替换味道',
  },
  {
    id: 'vip1_temp_sensitivity',
    title: '临时敏感度修改',
    description: '临时修改被催眠者一个部位的敏感度.',
    tier: 'VIP1',
    costType: 'PER_MINUTE',
    costValue: 5,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入要修改的部位',
  },
  {
    id: 'vip1_truth_serum',
    title: '吐真',
    description: '强制被催眠者说出内心真实想法.',
    tier: 'VIP1',
    costType: 'PER_MINUTE',
    costValue: 4,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '想问的问题 / 引导语',
  },
  {
    id: 'vip1_estrus',
    title: '发情',
    description: '强制被催眠者发情.',
    tier: 'VIP1',
    costType: 'ONE_TIME',
    costValue: 1,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入要增加的发情值',
  },
  {
    id: 'vip1_memory_erase',
    title: '记忆消除',
    description: '消除一段时间内的记忆, 如果时间太长目标可能会因为记忆缺失产生怀疑.',
    tier: 'VIP1',
    costType: 'ONE_TIME',
    costValue: 5,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入要清除的记忆时长',
  },

  // VIP 2
  {
    id: 'vip2_medium',
    title: '中级一般催眠',
    description:
      '被催眠者无意识遵循简单指示, 可以指令被催眠对象一般不愿意的指示, 不能指令极端不愿意的行为, 强行指令会退出催眠.',
    tier: 'VIP2',
    costType: 'PER_MINUTE',
    costValue: 10,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip2_pleasure',
    title: '快感赋予',
    description: '给予一个部位无来源的快感.',
    tier: 'VIP2',
    costType: 'PER_MINUTE',
    costValue: 5,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '部位',
  },
  {
    id: 'vip2_ghost_hand',
    title: '幽灵手',
    description: '让被催眠者错觉自己一直在被看不见的手玩弄.',
    tier: 'VIP2',
    costType: 'PER_MINUTE',
    costValue: 10,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip2_body_lock',
    title: '身体固定',
    description: '强行让被催眠者身体无法行动, 但意识会保持清醒.',
    tier: 'VIP2',
    costType: 'PER_MINUTE',
    costValue: 12,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip2_pain_to_pleasure',
    title: '痛觉转化',
    description: '将痛觉转换为快感.',
    tier: 'VIP2',
    costType: 'PER_MINUTE',
    costValue: 10,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip2_emperors_new_clothes',
    title: '皇帝的新衣',
    description: '让被催眠着没穿着衣服的情况下觉得自己穿着衣服.',
    tier: 'VIP2',
    costType: 'PER_MINUTE',
    costValue: 10,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip2_new_emperor',
    title: '新衣的皇帝',
    description: '让被催眠着在穿着衣服的情况下觉得自己没穿衣服.',
    tier: 'VIP2',
    costType: 'PER_MINUTE',
    costValue: 10,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },

  // VIP 3
  {
    id: 'vip3_forced',
    title: '强制高潮',
    description: '直接让被催眠者强制高潮.',
    tier: 'VIP3',
    costType: 'ONE_TIME',
    costValue: 100,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip3_orgasm_ban',
    title: '绝顶禁止',
    description: '永远无法高潮 (寸止).',
    tier: 'VIP3',
    costType: 'ONE_TIME',
    costValue: 300,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip3_visual_filter',
    title: '幻视滤镜',
    description: '被催眠者会将使用者看作是其他人.',
    tier: 'VIP3',
    costType: 'PER_MINUTE',
    costValue: 25,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip3_conditioned_reflex',
    title: '条件反射植入',
    description: '让被催眠者在特定的刺激下作出特定的条件反射行为.',
    tier: 'VIP3',
    costType: 'ONE_TIME',
    costValue: 300,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '触发条件 -> 反射行为',
  },
  {
    id: 'vip3_temp_common_sense',
    title: '限时常识修改',
    description: '在一定时间内修改被催眠者的一项常识.',
    tier: 'VIP3',
    costType: 'PER_MINUTE',
    costValue: 10,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入要修改的常识...',
  },
  {
    id: 'vip3_shame_invert',
    title: '羞耻心反转',
    description: '将羞耻感直接转化为快感.',
    tier: 'VIP3',
    costType: 'PER_MINUTE',
    costValue: 10,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip3_temp_false_memory',
    title: '临时虚假记忆',
    description: '给被催眠者临时植入一段记忆.',
    tier: 'VIP3',
    costType: 'ONE_TIME',
    costValue: 250,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入要植入的记忆...',
  },
  {
    id: 'vip3_pseudo_time_stop',
    title: '伪时停',
    description: '让被催眠者在当前的状态停止活动和意识, 快感会累计到结束时一起释放.',
    tier: 'VIP3',
    costType: 'PER_MINUTE',
    costValue: 30,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },

  // VIP 4
  {
    id: 'vip4_advanced',
    title: '高级一般催眠',
    description: '被催眠者无意识遵循简单指示, 可以指令任何行为.',
    tier: 'VIP4',
    costType: 'PER_MINUTE',
    costValue: 40,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip4_closed_space_common_sense',
    title: '封闭空间常识修改',
    description: '修改封闭空间内的规则或常识.',
    tier: 'VIP4',
    costType: 'PER_MINUTE',
    costValue: 2,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入空间人数（数字）+ 要修改的规则/常识',
  },
  {
    id: 'vip4_excretion_control',
    title: '排泄控制',
    description: '必须在指定条件下才能排泄.',
    tier: 'VIP4',
    costType: 'ONE_TIME',
    costValue: 300,
    costCurrency: 'MC_POINTS',
    isEnabled: false,
    notePlaceholder: '输入排泄条件...',
  },
  {
    id: 'vip4_control_body_keep_conscious',
    title: '保留意识控制身体行动',
    description: '保留被催眠者意识的情况下, 强行控制被催眠者的身体.',
    tier: 'VIP4',
    costType: 'PER_MINUTE',
    costValue: 50,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip4_control_body_no_conscious',
    title: '不保留意识控制身体行动',
    description: '在被催眠者无意识的情况下, 强行控制被催眠者的身体.',
    tier: 'VIP4',
    costType: 'PER_MINUTE',
    costValue: 50,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip4_cognitive_block',
    title: '认知妨碍',
    description: '心理学隐身, 不会被他人意识到存在.',
    tier: 'VIP4',
    costType: 'PER_MINUTE',
    costValue: 60,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },
  {
    id: 'vip4_fetish_implant',
    title: '性癖植入',
    description: '永久性地给被催眠者植入一个性癖.',
    tier: 'VIP4',
    costType: 'ONE_TIME',
    costValue: 800,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入要植入的性癖...',
  },
  {
    id: 'vip4_temp_personality',
    title: '临时人格植入',
    description: '临时将一个人格植入被催眠者.',
    tier: 'VIP4',
    costType: 'PER_MINUTE',
    costValue: 50,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入人格设定...',
  },
  {
    id: 'vip4_lactation',
    title: '泌乳诱导',
    description: '修改内分泌系统，让非哺乳期女性分泌乳汁.',
    tier: 'VIP4',
    costType: 'ONE_TIME',
    costValue: 500,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
  },

  // VIP 5
  {
    id: 'vip5_permanent',
    title: '永久常识修改',
    description: '永久修改被催眠者的一项常识.',
    tier: 'VIP5',
    costType: 'ONE_TIME',
    costValue: 2000,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入要修改的常识...',
  },
  {
    id: 'vip5_permanent_false_memory',
    title: '永久虚假记忆',
    description: '给被催眠者永久植入一段记忆.',
    tier: 'VIP5',
    costType: 'ONE_TIME',
    costValue: 1500,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入要植入的记忆...',
  },
  {
    id: 'vip5_permanent_personality',
    title: '永久人格植入',
    description: '永久将一个人格植入被催眠者.',
    tier: 'VIP5',
    costType: 'ONE_TIME',
    costValue: 3000,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入人格设定...',
  },
  {
    id: 'vip5_open_space_common_sense',
    title: '开放空间常识修改',
    description: '修改开放空间内的规则或常识.',
    tier: 'VIP5',
    costType: 'PER_MINUTE',
    costValue: 100,
    costCurrency: 'MC_ENERGY',
    isEnabled: false,
    notePlaceholder: '输入要修改的规则/常识...',
  },
];
